### ISSUE TITLE
Remove containment for `catalogs/accessPackages`

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#338]
Containment on `catalogs/accessPackages` should be removed since requests made to `POST /identityGovernance/entitlementManagement/catalogs/{accessPackageCatalog-id}/accessPackages/{accessPackage-id}/assignmentPolicies` fail with `No HTTP resource was found that matches the request URI 'https://igaelm-asev3-ecapi-neu.igaelm-asev3-environment-neu.p.azurewebsites.net/api/v1/catalogs('id')/accessPackages('id)/assignmentPolicies'.` error message.

The error message suggests that the workload does not support path. Unfortunately, the path is currently surfaced as supported in the CSDL which leads to the overgeneration seen at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1970:

#### CSDL
``` xml
<EntityType Name="accessPackageCatalog" BaseType="graph.entity">
  <Property Name="catalogType" Type="graph.accessPackageCatalogType" />
  <Property Name="createdDateTime" Type="Edm.DateTimeOffset" />
  <Property Name="description" Type="Edm.String" />
  <Property Name="displayName" Type="Edm.String" />
  <Property Name="isExternallyVisible" Type="Edm.Boolean" />
  <Property Name="modifiedDateTime" Type="Edm.DateTimeOffset" />
  <Property Name="state" Type="graph.accessPackageCatalogState" />
  <NavigationProperty Name="accessPackages" Type="Collection(graph.accessPackage)" ContainsTarget="true" /> <!--Should not be contained-->
</EntityType>
```

#### OpenAPI
``` yml
  '/identityGovernance/entitlementManagement/catalogs/{accessPackageCatalog-id}/accessPackages/{accessPackage-id}/assignmentPolicies':
    post:
      summary: Create new navigation property to assignmentPolicies for identityGovernance
      operationId: identityGovernance.entitlementManagement.catalogs.accessPackages_CreateAssignmentPolicies
      ...
    get:
      summary: Get assignmentPolicies from identityGovernance
      operationId: identityGovernance.entitlementManagement.catalogs.accessPackages_ListAssignmentPolicies
      ...
```

As per the API reference - https://learn.microsoft.com/en-us/graph/api/resources/accesspackagecatalog?view=graph-rest-1.0#relationships:
><html>
<body>

Relationship | Type | Description
-- | -- | --
accessPackages | accessPackage collection | The access packages in this catalog. Read-only. Nullable.

</body>
</html>

### Additional Notes
Workload owner's input is needed to validate the above assumption.

The issue is closely related to https://github.com/microsoftgraph/msgraph-metadata/issues/243.
