### ISSUE TITLE
Invalid path `/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues`

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/msgraph-metadata#435]
Open API specification contains description of `/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues` endpoint

```
  '/admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues':
    description: Provides operations to manage the issues property of the microsoft.graph.serviceHealth entity.
    get:
      ...
    post:
      ...
    parameters:
      - name: serviceHealth-id
        in: path
        description: The unique identifier of serviceHealth
        required: true
        schema:
          type: string
        x-ms-docs-key-type: serviceHealth
```

But request `GET /admin/serviceAnnouncement/healthOverviews/{serviceHealth-id}/issues` fails with `404`

```
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2023-09-20T12:32:06",
            "request-id": "2aeda9ef-547f-4caf-93a2-979c53c72c31",
            "client-request-id": "a4a3c3ae-1b08-8ce5-40d0-a9425c5edb52"
        }
    }
}
```

In fact, issues can be accessed only by calling

`GET /admin/serviceAnnouncement/issues`

Also `post` operation doesn't make sense, because service health is 'read-only' endpoint
