### ISSUE TITLE
Missing key UserExtend for Enum AccessPackageRequestType

### ISSUE THREAD

**Issue by shemogumbe** [microsoftgraph/msgraph-metadata#661]
Fixes https://github.com/microsoftgraph/msgraph-sdk-python/issues/838

Raised in python, the missing key UserExtend for Enum AccessPackageRequestType affects all SDKs.

While generation is fine , it maps the enum definition in the OpenAPI file:
```yaml
microsoft.graph.accessPackageRequestType:
      title: accessPackageRequestType
      enum:
        - notSpecified
        - userAdd
        - userUpdate
        - userRemove
        - adminAdd
        - adminUpdate
        - adminRemove
        - systemAdd
        - systemUpdate
        - systemRemove
        - onBehalfAdd
        - unknownFutureValue
      type: string
```
To the generated Python Enum Model as:
```python
from enum import Enum

class AccessPackageRequestType(str, Enum):
    NotSpecified = "notSpecified",
    UserAdd = "userAdd",
    UserUpdate = "userUpdate",
    UserRemove = "userRemove",
    AdminAdd = "adminAdd",
    AdminUpdate = "adminUpdate",
    AdminRemove = "adminRemove",
    SystemAdd = "systemAdd",
    SystemUpdate = "systemUpdate",
    SystemRemove = "systemRemove",
    OnBehalfAdd = "onBehalfAdd",
    UnknownFutureValue = "unknownFutureValue",

```

**More Details**
The openapi.yaml shows that UserExtend exists in the description, but it does not exist in the definition as shown above.
![image](https://github.com/user-attachments/assets/2db14a20-d92b-4116-b489-1e8551bfbfd2)

**Workload owner or metadata update required**
Checking the description, seems the key has not been added by the workload owner as well:
![image (1)](https://github.com/user-attachments/assets/e8fc7a16-8050-4dbe-9579-4c968bbba6c4)

**Solution**
Adding this will automatically solve this for all SDKs.
